version: "3.7"
services:
        airflow:
                build: ./airflow
                image: airflow:local
                volumes:
                        - logs-data:/airflow/logs
                        - sqlite-data:/airflow/data
                ports:
                        - "8080:8080"

                expose:
                        - "8080"


volumes:
        sqlite-data:
        logs-data:
