version: "3.7"
services:
        airflow:
                build: 
                        context: ./airflow
                        args:
                                AIRFLOW_HOME: ${AIRFLOW_HOME}
                                AIRFLOW__CORE__SQL_ALCHEMY_CON: ${AIRFLOW_SQLITE_STR}

                image: airflow:local
                volumes:
                        - logs-data:${AIRFLOW_LOGS_LOCATION}
                        - sqlite-data:${AIRFLOW_SQLITE_LOCATION}
                ports:
                        - ${AIRFLOW_WEB_PORT}:${AIRFLOW_WEB_PORT}
                expose:
                        - ${AIRFLOW_WEB_PORT}
                

volumes:
        sqlite-data:
        logs-data:
