version: "3.7"
services:
  airflow:
    build:
      context: ./airflow
      args:
        AIRFLOW_HOME: ${AIRFLOW_HOME}

    image: airflow:local
    volumes:
      - airflow-logs:${AIRFLOW_LOGS_PATH}
    ports:
      - ${AIRFLOW_WEB_PORT}:${AIRFLOW_WEB_PORT}
    expose:
      - ${AIRFLOW_WEB_PORT}
    depends_on:
      - airflow-db
    links:
      - airflow-db:airflow-db

  airflow-db:
    image: mysql:5.7.26
    environment:
      MYSQL_ROOT_PASSWORD: root_passwd
      MYSQL_DATABASE: airflow_db
      MYSQL_USER: airflow_user
      MYSQL_PASSWORD: airflow_password
    command: --explicit_defaults_for_timestamp=1 --pid-file=/var/run/mysqld/mysqld
    volumes:
      - airflow-db:${AIRFLOW_DATABASE_PATH}
    ports:
      - ${AIRFLOW_DATABASE_PORT}:${AIRFLOW_DATABASE_PORT}
    expose:
      - ${AIRFLOW_DATABASE_PORT}

    restart: always
volumes:
  airflow-db:
    driver: local
  airflow-logs:
    driver: local
