version: "2"
services:
        airflow:
                build: ./airflow
                command: ["airflow", "webserver", "--port", "8080"]
                ports:
                        - "8080:8080"


